# Generated by Django 4.2.13 on 2024-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eigth', 'Eigth'), ('Ninth', 'Ninth'), ('Tenth', 'Tenth'), ('Eleventh', 'Eleventh'), ('Twelfth', 'Twelfth')], max_length=255),
        ),
    ]
