# Generated by Django 4.2.13 on 2024-07-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='discription',
            new_name='description',
        ),
    ]
