# Generated by Django 4.2.13 on 2024-07-18 00:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logs',
            new_name='Log',
        ),
    ]
