# Generated by Django 4.2.13 on 2024-07-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_remove_log_curriculum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
