# Generated by Django 4.2.13 on 2024-07-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_alter_log_hour_type_alter_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='location',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], default='Home', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective')], max_length=255),
        ),
    ]
