# Generated by Django 4.2.13 on 2024-07-18 01:06

from django.db import migrations

def add_subjects(apps, schema_editor):
    Subject = apps.get_model('logger', 'Subject')
    subjects = [
        {'name': 'Math', 'type': 'Core'},
        {'name': 'Science', 'type': 'Core'},
        {'name': 'Social Studies', 'type': 'Core'},
        {'name': 'Language Arts', 'type': 'Core'},
        {'name': 'Reading', 'type': 'Core'}
    ]

    for subject in subjects:
        Subject.objects.update_or_create(name=subject['name'], defaults={'type': subject['type']})


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_delete_curriculum'),
    ]

    operations = [
        migrations.RunPython(add_subjects),
    ]
