# Generated by Django 4.2.13 on 2024-07-19 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_log_location_alter_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='required_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.requiredsubjects'),
        ),
    ]
