# Generated by Django 4.2.13 on 2024-07-19 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_log_required_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.subject'),
        ),
    ]
